### ISSUE TITLE
Rename Items in Settings 

### ISSUE THREAD

**Issue by Neldrion** [SSchulze1989/iRLeagueManager#46]
**Describe the solution you'd like**
For new users rename the following in the SETTINGS page

Scoring ---> Race Results?
Scoring Tables ---> Championships
Results per Race ---> Drivers per Race
Take group average ---> Use Team average points
Scoring Kind ---> Driver / Team Points
Average Race Nr  ---> i dont understand

**Comment by SSchulze1989** [comment]
Thanks, I take you comments into account.
You can follow progress on this on this issue #26.
