### ISSUE TITLE
Rearrange main topics on the leftside bar

### ISSUE THREAD

**Issue by Neldrion** [SSchulze1989/iRLeagueManager#47]
**Describe the solution you'd like**
1. Rearrange the leftside bar in the order in which people work through the season, for example in the following order.
2. Rename items (old name in brackets)

- Settings
- Schedules
- Calendar (Race Calendar)
- Results
- Accidents (Reviews)
- Standings
- Teams
- Stats

**Comment by SSchulze1989** [comment]
Thx. This will be available in next release.

**Comment by Neldrion** [comment]
Another proposal:

Calender, Stats and Team could be below a horizontal line because they are slighty other category than the rest

- Settings
- Schedules
- Results
- Accidents
- Standings
----------------------------
- Calendar
- Stats
- Teams
