### ISSUE TITLE
Login - Remember Name and Password

### ISSUE THREAD

**Issue by Neldrion** [SSchulze1989/iRLeagueManager#48]
**Is your feature request related to a problem? Please describe.**
I made a lot of accounts because i did not write up my password.
Today i finally wrote down my password.

**Describe the solution you'd like**
Possible to remember User locally at Login Screen?

**Comment by SSchulze1989** [comment]
Thx. This will be possible in some time but is not top priority.

**Comment by SSchulze1989** [comment]
I have searched a bit on the net and found a possible solution that leverages Windows credential manager.  I will try implementing this today, maybe get it in the next release.

**Comment by SSchulze1989** [comment]
Got this implemented.
Will be part of v0.5.2 release
