### ISSUE TITLE
Reviews - Remove description field (Reverted)

### ISSUE THREAD

**Issue by Neldrion** [SSchulze1989/iRLeagueManager#52]
When creating an incident, the field "description" is not really necessary, the first steward should use his "comment" to describe the situation.

**Comment by Neldrion** [comment]
The Incident Type / Category "e.g. Contact in Corner" is enough base description.

**Comment by SSchulze1989** [comment]
Yes I agree. I will remove the description.

**Comment by SSchulze1989** [comment]
Someone raised the question where you would put a text from a driver reporting an issue. That driver could not add a comment.
I think it would be valid to have this description window back for things like that.
Comments should then only be used for discussion.

**Comment by SSchulze1989** [comment]
Gonna add the description field again for now. 
In the future the description will be shown directly on the review card.
