### ISSUE TITLE
Automated Amateur Championship (e.g. Heisse Eisen)

### ISSUE THREAD

**Issue by Neldrion** [SSchulze1989/iRLeagueManager#63]
**Describe the solution you'd like**
Take drivers <1800 irating at their first season race to separate championship for amateurs.

**Comment by SSchulze1989** [comment]
This iw something long planned in the pipeline. But it will need some further time to implement.
The goal is to make this available through filters.
You can set one or more filters on a scoring and chose options like current iratin, irating at season start, minimum laptime etc. 
I want to make this really customizable and have the whole thing planned out basically. 
Maybe around 1 or 2 months to go, depending on much how bugs are popping up in the next time ;)

**Comment by SSchulze1989** [comment]
The current csv upload does not provide info on the irating. So there is no way with this to implement an irating based filter because of missing information.
This means the JSON import function has to be implemented first.
