### ISSUE TITLE
Review - Incident Type - Dropdownlist

### ISSUE THREAD

**Issue by Neldrion** [SSchulze1989/iRLeagueManager#68]
**Describe the solution you'd like**
When creating a Review, the incident Type field can have preset categories to choose from:

- Auffahrunfall
- Gefährliches Verhalten (Ausrollen ohne Benzin)
- Gefährliches Verhalten (beschädigtes Fahrzeug)
- Gefährliches Verhalten (Bremse nicht gehalten)
- Gefährliches Verhalten (Stehenbleiben beim Start)
- Gefährliches Verhalten (unsicheres Einfädeln)
- Gefährliches Verhalten (Verhalten unter gelber Flagge)
- Kontakt auf Gerade
- Kontakt beim Anbremsen
- Kontakt in Kurve
- Kontakt nach Fahrfehler
- Unsportliches Verhalten (Blocking)

**Comment by SSchulze1989** [comment]
This is supposed to come with a new option on settings to make a custom collection of these incident kinds.
But for now i will add it as a static List, thats not much work.
- [ ] Add static dropdown list to ReviewEdit
